apiVersion: apps/v1
kind: Deployment
metadata:
  name: fox-web-dev
  labels:
    app: fox-web-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fox-web-dev
  template:
    metadata:
      labels:
        app: fox-web-dev
    spec:
      imagePullSecrets:
      - name: docker-registry-login
      initContainers:
      - name: assets
        image: docker-registry.192-168-33-10.nip.io/fox-web-assets:latest
        volumeMounts:
        - mountPath: /assets
          name: assets
        command: ["sh", "-c", "cp -r /tmp/assets/* /assets"]
      containers:
      - name: nginx
        image: nginx:1.17.7
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: assets
        ports:
          - containerPort: 80
      volumes:
      - name: assets
        emptyDir: {}
        
    

